#!/bin/bash

function usage()
{
        echo -e "usage: demo_resnext [arguments]\n"
        echo -e "mandatory arguments:\n"
        echo -e "  -d <data_type>,    --dtype <data_type>          Data type, possible values: fp32, bf16"
}

__data_type="0"

while [ -n "$1" ];
    do
        case $1 in
        -d  | --dtype )
            shift
            __data_type=$1
            ;;
        esac
        shift
    done

export TF_ENABLE_BF16_CONVERSION=0
if [ $__data_type == "bf16" ]; then
    export TF_ENABLE_BF16_CONVERSION=1
elif [ $__data_type != "fp32" ]; then
    echo -e "Incorrect data type\n"
    usage
    exit 1;
fi

source resnext_common.sh
