# @package _group_

common:
  fp16: false
  log_format: simple
  log_interval: 1
  hpu: true
  hpu_lazy_mode: true
  seed: 1
  hmp: true
  hmp_bf16: ../examples/wav2vec/config/pretraining/ops_bf16.txt
  hmp_fp32: ../examples/wav2vec/config/pretraining/ops_fp32.txt
  hmp_verbose: false
  hmp_opt_level: O1

checkpoint:
  save_interval_updates: 25000
  keep_interval_updates: 1
  no_epoch_checkpoints: true

task:
  _name: audio_pretraining
  data: ???
  max_sample_size: 250000
  min_sample_size: 32000
  normalize: true
  num_batch_buckets: 7
  precompute_mask_indices: true
  enable_padding: true
  inferred_w2v_config:
      mask_prob: 0.65
      mask_selection: 'static'
      mask_other: 0
      mask_channel_prob: 0.0

dataset:
  num_workers: 6
  batch_size: 16
  max_tokens: 1400000
  skip_invalid_size_inputs_valid_test: true

distributed_training:
  distributed_world_size: 1
  ddp_backend: pytorch_ddp

criterion:
  _name: wav2vec
  infonce: true
  log_keys: ["prob_perplexity","code_perplexity","temp"]
  loss_weights: [0.1, 10]

optimization:
  max_update: 400000
  lr: [0.0005]
  update_freq: [64]

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-06
  weight_decay: 0.01

lr_scheduler:
  _name: polynomial_decay
  warmup_updates: 32000

model:
  _name: wav2vec2
  quantize_targets: true
  final_dim: 256
  encoder_layerdrop: 0.0
  dropout_input: 0.1
  dropout_features: 0.1
  feature_grad_mult: 0.1
  encoder_embed_dim: 768
