model: "resnet_estimator"
env_variables:
  TF_ALLOW_CONTROL_EDGES_IN_HABANA_OPS: 1
  TF_PRELIMINARY_CLUSTER_SIZE: 200
  USE_LARS_OPTIMIZER: 0

parameters:
  num_gpus: 1
  data_dir: "/root/tensorflow_datasets/imagenet/tf_records"
  distribution_strategy: "off"
  data_format: "channels_last"
  save_checkpoint_steps: 5005
  batch_size: 256
  resnet_size: 50
  train_epochs: 90
  model_dir: "/tmp/resnet_estimator"
  display_steps: 100
  experimental_preloading: 1
  use_horovod: false
  use_train_and_evaluate: false
  epochs_between_evals: 8
  enable_lars: false
  dummy_epoch: false